/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SubjectId = IDL.Nat;
export const ChapterId = IDL.Nat;
export const QuestionId = IDL.Nat;
export const AttemptId = IDL.Nat;
export const Timestamp = IDL.Int;
export const UserId = IDL.Principal;
export const QuestionResult = IDL.Record({
  'timeSpent' : IDL.Nat,
  'userAnswer' : IDL.Text,
  'isCorrect' : IDL.Bool,
  'questionId' : QuestionId,
});
export const SessionId = IDL.Nat;
export const QuizAttempt = IDL.Record({
  'completedAt' : Timestamp,
  'attemptId' : AttemptId,
  'userId' : UserId,
  'questionResults' : IDL.Vec(QuestionResult),
  'chapterId' : ChapterId,
  'score' : IDL.Float64,
  'totalQuestions' : IDL.Nat,
  'subjectId' : SubjectId,
  'correctAnswers' : IDL.Nat,
  'sessionId' : SessionId,
  'timeTaken' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Chapter = IDL.Record({
  'id' : ChapterId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'subjectId' : SubjectId,
});
export const StudentProfile = IDL.Record({
  'userId' : UserId,
  'lastActivity' : Timestamp,
  'bestScore' : IDL.Float64,
  'totalAttempts' : IDL.Nat,
  'averageScore' : IDL.Float64,
});
export const Difficulty = IDL.Variant({
  'Easy' : IDL.Null,
  'Hard' : IDL.Null,
  'Medium' : IDL.Null,
});
export const QuestionType = IDL.Variant({
  'MultipleChoice' : IDL.Null,
  'FillInBlank' : IDL.Null,
  'TrueFalse' : IDL.Null,
});
export const Question = IDL.Record({
  'id' : QuestionId,
  'difficulty' : Difficulty,
  'correctAnswer' : IDL.Text,
  'chapterId' : ChapterId,
  'questionText' : IDL.Text,
  'questionType' : QuestionType,
  'solution' : IDL.Opt(IDL.Text),
  'options' : IDL.Vec(IDL.Text),
});
export const Subject = IDL.Record({
  'id' : SubjectId,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const StartSessionInput = IDL.Record({
  'timeLimit' : IDL.Nat,
  'chapterId' : ChapterId,
  'questionCount' : IDL.Nat,
});
export const SubmitAnswerInput = IDL.Record({
  'timeSpent' : IDL.Nat,
  'userAnswer' : IDL.Text,
  'questionId' : QuestionId,
});

export const idlService = IDL.Service({
  'addChapter' : IDL.Func(
      [SubjectId, IDL.Text],
      [IDL.Variant({ 'ok' : ChapterId, 'err' : IDL.Text })],
      [],
    ),
  'addQuestion' : IDL.Func(
      [
        ChapterId,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
      ],
      [IDL.Variant({ 'ok' : QuestionId, 'err' : IDL.Text })],
      [],
    ),
  'addSubject' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : SubjectId, 'err' : IDL.Text })],
      [],
    ),
  'bulkImportQuestions' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'deleteChapter' : IDL.Func(
      [ChapterId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteQuestion' : IDL.Func(
      [QuestionId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteSubject' : IDL.Func(
      [SubjectId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'getAdminPrincipal' : IDL.Func([], [IDL.Text], ['query']),
  'getAttemptDetail' : IDL.Func([AttemptId], [IDL.Opt(QuizAttempt)], ['query']),
  'getCallerPrincipal' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getChapters' : IDL.Func([SubjectId], [IDL.Vec(Chapter)], ['query']),
  'getMyAttempts' : IDL.Func([], [IDL.Vec(QuizAttempt)], ['query']),
  'getMyProfile' : IDL.Func([], [StudentProfile], ['query']),
  'getQuestions' : IDL.Func(
      [ChapterId, IDL.Nat],
      [IDL.Vec(Question)],
      ['query'],
    ),
  'getSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitQuizAttempt' : IDL.Func(
      [StartSessionInput, IDL.Vec(SubmitAnswerInput)],
      [QuizAttempt],
      [],
    ),
  'updateChapter' : IDL.Func(
      [ChapterId, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateSubject' : IDL.Func(
      [SubjectId, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SubjectId = IDL.Nat;
  const ChapterId = IDL.Nat;
  const QuestionId = IDL.Nat;
  const AttemptId = IDL.Nat;
  const Timestamp = IDL.Int;
  const UserId = IDL.Principal;
  const QuestionResult = IDL.Record({
    'timeSpent' : IDL.Nat,
    'userAnswer' : IDL.Text,
    'isCorrect' : IDL.Bool,
    'questionId' : QuestionId,
  });
  const SessionId = IDL.Nat;
  const QuizAttempt = IDL.Record({
    'completedAt' : Timestamp,
    'attemptId' : AttemptId,
    'userId' : UserId,
    'questionResults' : IDL.Vec(QuestionResult),
    'chapterId' : ChapterId,
    'score' : IDL.Float64,
    'totalQuestions' : IDL.Nat,
    'subjectId' : SubjectId,
    'correctAnswers' : IDL.Nat,
    'sessionId' : SessionId,
    'timeTaken' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Chapter = IDL.Record({
    'id' : ChapterId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'subjectId' : SubjectId,
  });
  const StudentProfile = IDL.Record({
    'userId' : UserId,
    'lastActivity' : Timestamp,
    'bestScore' : IDL.Float64,
    'totalAttempts' : IDL.Nat,
    'averageScore' : IDL.Float64,
  });
  const Difficulty = IDL.Variant({
    'Easy' : IDL.Null,
    'Hard' : IDL.Null,
    'Medium' : IDL.Null,
  });
  const QuestionType = IDL.Variant({
    'MultipleChoice' : IDL.Null,
    'FillInBlank' : IDL.Null,
    'TrueFalse' : IDL.Null,
  });
  const Question = IDL.Record({
    'id' : QuestionId,
    'difficulty' : Difficulty,
    'correctAnswer' : IDL.Text,
    'chapterId' : ChapterId,
    'questionText' : IDL.Text,
    'questionType' : QuestionType,
    'solution' : IDL.Opt(IDL.Text),
    'options' : IDL.Vec(IDL.Text),
  });
  const Subject = IDL.Record({
    'id' : SubjectId,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const StartSessionInput = IDL.Record({
    'timeLimit' : IDL.Nat,
    'chapterId' : ChapterId,
    'questionCount' : IDL.Nat,
  });
  const SubmitAnswerInput = IDL.Record({
    'timeSpent' : IDL.Nat,
    'userAnswer' : IDL.Text,
    'questionId' : QuestionId,
  });
  
  return IDL.Service({
    'addChapter' : IDL.Func(
        [SubjectId, IDL.Text],
        [IDL.Variant({ 'ok' : ChapterId, 'err' : IDL.Text })],
        [],
      ),
    'addQuestion' : IDL.Func(
        [
          ChapterId,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
        ],
        [IDL.Variant({ 'ok' : QuestionId, 'err' : IDL.Text })],
        [],
      ),
    'addSubject' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : SubjectId, 'err' : IDL.Text })],
        [],
      ),
    'bulkImportQuestions' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'deleteChapter' : IDL.Func(
        [ChapterId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteQuestion' : IDL.Func(
        [QuestionId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteSubject' : IDL.Func(
        [SubjectId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'getAdminPrincipal' : IDL.Func([], [IDL.Text], ['query']),
    'getAttemptDetail' : IDL.Func(
        [AttemptId],
        [IDL.Opt(QuizAttempt)],
        ['query'],
      ),
    'getCallerPrincipal' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getChapters' : IDL.Func([SubjectId], [IDL.Vec(Chapter)], ['query']),
    'getMyAttempts' : IDL.Func([], [IDL.Vec(QuizAttempt)], ['query']),
    'getMyProfile' : IDL.Func([], [StudentProfile], ['query']),
    'getQuestions' : IDL.Func(
        [ChapterId, IDL.Nat],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'getSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitQuizAttempt' : IDL.Func(
        [StartSessionInput, IDL.Vec(SubmitAnswerInput)],
        [QuizAttempt],
        [],
      ),
    'updateChapter' : IDL.Func(
        [ChapterId, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateSubject' : IDL.Func(
        [SubjectId, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };