/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AttemptId = bigint;
export interface Chapter {
  'id' : ChapterId,
  'name' : string,
  'description' : string,
  'subjectId' : SubjectId,
}
export type ChapterId = bigint;
export type Difficulty = { 'Easy' : null } |
  { 'Hard' : null } |
  { 'Medium' : null };
export interface Question {
  'id' : QuestionId,
  'difficulty' : Difficulty,
  'correctAnswer' : string,
  'chapterId' : ChapterId,
  'questionText' : string,
  'questionType' : QuestionType,
  'solution' : [] | [string],
  'options' : Array<string>,
}
export type QuestionId = bigint;
export interface QuestionResult {
  'timeSpent' : bigint,
  'userAnswer' : string,
  'isCorrect' : boolean,
  'questionId' : QuestionId,
}
export type QuestionType = { 'MultipleChoice' : null } |
  { 'FillInBlank' : null } |
  { 'TrueFalse' : null };
export interface QuizAttempt {
  'completedAt' : Timestamp,
  'attemptId' : AttemptId,
  'userId' : UserId,
  'questionResults' : Array<QuestionResult>,
  'chapterId' : ChapterId,
  'score' : number,
  'totalQuestions' : bigint,
  'subjectId' : SubjectId,
  'correctAnswers' : bigint,
  'sessionId' : SessionId,
  'timeTaken' : bigint,
}
export type SessionId = bigint;
export interface StartSessionInput {
  'timeLimit' : bigint,
  'chapterId' : ChapterId,
  'questionCount' : bigint,
}
export interface StudentProfile {
  'userId' : UserId,
  'lastActivity' : Timestamp,
  'bestScore' : number,
  'totalAttempts' : bigint,
  'averageScore' : number,
}
export interface Subject {
  'id' : SubjectId,
  'name' : string,
  'description' : string,
}
export type SubjectId = bigint;
export interface SubmitAnswerInput {
  'timeSpent' : bigint,
  'userAnswer' : string,
  'questionId' : QuestionId,
}
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserProfile { 'name' : string }
export interface _SERVICE {
  'addChapter' : ActorMethod<
    [SubjectId, string],
    { 'ok' : ChapterId } |
      { 'err' : string }
  >,
  'addQuestion' : ActorMethod<
    [ChapterId, string, string, Array<string>, string, string, [] | [string]],
    { 'ok' : QuestionId } |
      { 'err' : string }
  >,
  'addSubject' : ActorMethod<
    [string, string],
    { 'ok' : SubjectId } |
      { 'err' : string }
  >,
  'bulkImportQuestions' : ActorMethod<
    [string],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'deleteChapter' : ActorMethod<
    [ChapterId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteQuestion' : ActorMethod<
    [QuestionId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteSubject' : ActorMethod<
    [SubjectId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'getAdminPrincipal' : ActorMethod<[], string>,
  'getAttemptDetail' : ActorMethod<[AttemptId], [] | [QuizAttempt]>,
  'getCallerPrincipal' : ActorMethod<[], string>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getChapters' : ActorMethod<[SubjectId], Array<Chapter>>,
  'getMyAttempts' : ActorMethod<[], Array<QuizAttempt>>,
  'getMyProfile' : ActorMethod<[], StudentProfile>,
  'getQuestions' : ActorMethod<[ChapterId, bigint], Array<Question>>,
  'getSubjects' : ActorMethod<[], Array<Subject>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitQuizAttempt' : ActorMethod<
    [StartSessionInput, Array<SubmitAnswerInput>],
    QuizAttempt
  >,
  'updateChapter' : ActorMethod<
    [ChapterId, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateSubject' : ActorMethod<
    [SubjectId, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];