/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface StartSessionInput {
    timeLimit: bigint;
    chapterId: ChapterId;
    questionCount: bigint;
}
export type AttemptId = bigint;
export type QuestionId = bigint;
export type SessionId = bigint;
export interface Chapter {
    id: ChapterId;
    name: string;
    description: string;
    subjectId: SubjectId;
}
export type ChapterId = bigint;
export interface QuestionResult {
    timeSpent: bigint;
    userAnswer: string;
    isCorrect: boolean;
    questionId: QuestionId;
}
export type UserId = Principal;
export interface StudentProfile {
    userId: UserId;
    lastActivity: Timestamp;
    bestScore: number;
    totalAttempts: bigint;
    averageScore: number;
}
export interface SubmitAnswerInput {
    timeSpent: bigint;
    userAnswer: string;
    questionId: QuestionId;
}
export interface QuizAttempt {
    completedAt: Timestamp;
    attemptId: AttemptId;
    userId: UserId;
    questionResults: Array<QuestionResult>;
    chapterId: ChapterId;
    score: number;
    totalQuestions: bigint;
    subjectId: SubjectId;
    correctAnswers: bigint;
    sessionId: SessionId;
    timeTaken: bigint;
}
export interface Question {
    id: QuestionId;
    difficulty: Difficulty;
    correctAnswer: string;
    chapterId: ChapterId;
    questionText: string;
    questionType: QuestionType;
    options: Array<string>;
}
export type SubjectId = bigint;
export interface UserProfile {
    name: string;
}
export interface Subject {
    id: SubjectId;
    name: string;
    description: string;
}
export enum Difficulty {
    Easy = "Easy",
    Hard = "Hard",
    Medium = "Medium"
}
export enum QuestionType {
    MultipleChoice = "MultipleChoice",
    FillInBlank = "FillInBlank",
    TrueFalse = "TrueFalse"
}
export interface backendInterface {
    addChapter(subjectId: SubjectId, name: string): Promise<{
        __kind__: "ok";
        ok: ChapterId;
    } | {
        __kind__: "err";
        err: string;
    }>;
    addQuestion(chapterId: ChapterId, text: string, questionType: string, options: Array<string>, correctAnswer: string, difficulty: string): Promise<{
        __kind__: "ok";
        ok: QuestionId;
    } | {
        __kind__: "err";
        err: string;
    }>;
    addSubject(name: string, description: string): Promise<{
        __kind__: "ok";
        ok: SubjectId;
    } | {
        __kind__: "err";
        err: string;
    }>;
    bulkImportQuestions(data: string): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteChapter(id: ChapterId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteQuestion(id: QuestionId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteSubject(id: SubjectId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getAdminPrincipal(): Promise<string>;
    getAttemptDetail(attemptId: AttemptId): Promise<QuizAttempt | null>;
    getCallerPrincipal(): Promise<string>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getChapters(subjectId: SubjectId): Promise<Array<Chapter>>;
    getMyAttempts(): Promise<Array<QuizAttempt>>;
    getMyProfile(): Promise<StudentProfile>;
    getQuestions(chapterId: ChapterId, count: bigint): Promise<Array<Question>>;
    getSubjects(): Promise<Array<Subject>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitQuizAttempt(sessionInput: StartSessionInput, answers: Array<SubmitAnswerInput>): Promise<QuizAttempt>;
    updateChapter(id: ChapterId, name: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateSubject(id: SubjectId, name: string, description: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
}
import type { ChapterId as _ChapterId, Difficulty as _Difficulty, Question as _Question, QuestionId as _QuestionId, QuestionType as _QuestionType, QuizAttempt as _QuizAttempt, SubjectId as _SubjectId, UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addChapter(arg0: SubjectId, arg1: string): Promise<{
        __kind__: "ok";
        ok: ChapterId;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addChapter(arg0, arg1);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addChapter(arg0, arg1);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async addQuestion(arg0: ChapterId, arg1: string, arg2: string, arg3: Array<string>, arg4: string, arg5: string): Promise<{
        __kind__: "ok";
        ok: QuestionId;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addQuestion(arg0, arg1, arg2, arg3, arg4, arg5);
                return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addQuestion(arg0, arg1, arg2, arg3, arg4, arg5);
            return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async addSubject(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: SubjectId;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addSubject(arg0, arg1);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSubject(arg0, arg1);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async bulkImportQuestions(arg0: string): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkImportQuestions(arg0);
                return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkImportQuestions(arg0);
            return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteChapter(arg0: ChapterId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteChapter(arg0);
                return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteChapter(arg0);
            return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteQuestion(arg0: QuestionId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteQuestion(arg0);
                return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteQuestion(arg0);
            return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteSubject(arg0: SubjectId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSubject(arg0);
                return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSubject(arg0);
            return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminPrincipal(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminPrincipal();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminPrincipal();
            return result;
        }
    }
    async getAttemptDetail(arg0: AttemptId): Promise<QuizAttempt | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttemptDetail(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttemptDetail(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerPrincipal(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerPrincipal();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerPrincipal();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChapters(arg0: SubjectId): Promise<Array<Chapter>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChapters(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChapters(arg0);
            return result;
        }
    }
    async getMyAttempts(): Promise<Array<QuizAttempt>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyAttempts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyAttempts();
            return result;
        }
    }
    async getMyProfile(): Promise<StudentProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return result;
        }
    }
    async getQuestions(arg0: ChapterId, arg1: bigint): Promise<Array<Question>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuestions(arg0, arg1);
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuestions(arg0, arg1);
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubjects(): Promise<Array<Subject>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubjects();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubjects();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitQuizAttempt(arg0: StartSessionInput, arg1: Array<SubmitAnswerInput>): Promise<QuizAttempt> {
        if (this.processError) {
            try {
                const result = await this.actor.submitQuizAttempt(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitQuizAttempt(arg0, arg1);
            return result;
        }
    }
    async updateChapter(arg0: ChapterId, arg1: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateChapter(arg0, arg1);
                return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateChapter(arg0, arg1);
            return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSubject(arg0: SubjectId, arg1: string, arg2: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSubject(arg0, arg1, arg2);
                return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSubject(arg0, arg1, arg2);
            return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Difficulty_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Difficulty): Difficulty {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_QuestionType_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuestionType): QuestionType {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Question_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Question): Question {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_QuizAttempt]): QuizAttempt | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _QuestionId;
    difficulty: _Difficulty;
    correctAnswer: string;
    chapterId: _ChapterId;
    questionText: string;
    questionType: _QuestionType;
    options: Array<string>;
}): {
    id: QuestionId;
    difficulty: Difficulty;
    correctAnswer: string;
    chapterId: ChapterId;
    questionText: string;
    questionType: QuestionType;
    options: Array<string>;
} {
    return {
        id: value.id,
        difficulty: from_candid_Difficulty_n11(_uploadFile, _downloadFile, value.difficulty),
        correctAnswer: value.correctAnswer,
        chapterId: value.chapterId,
        questionText: value.questionText,
        questionType: from_candid_QuestionType_n13(_uploadFile, _downloadFile, value.questionType),
        options: value.options
    };
}
function from_candid_variant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _ChapterId;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: ChapterId;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Easy: null;
} | {
    Hard: null;
} | {
    Medium: null;
}): Difficulty {
    return "Easy" in value ? Difficulty.Easy : "Hard" in value ? Difficulty.Hard : "Medium" in value ? Difficulty.Medium : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    MultipleChoice: null;
} | {
    FillInBlank: null;
} | {
    TrueFalse: null;
}): QuestionType {
    return "MultipleChoice" in value ? QuestionType.MultipleChoice : "FillInBlank" in value ? QuestionType.FillInBlank : "TrueFalse" in value ? QuestionType.TrueFalse : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _QuestionId;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: QuestionId;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _SubjectId;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: SubjectId;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Question>): Array<Question> {
    return value.map((x)=>from_candid_Question_n9(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
